language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_3b9733f1f5a9_key -iv $encrypted_3b9733f1f5a9_iv
  -in app/secrets.tar.enc -out app/secrets.tar -d
- tar xvf app/secrets.tar -c app
script:
- if [ $TRAVIS_PULL_REQUEST ]
- then
- echo "Pull request, not deploying"
- "./gradlew assembleProduction"
- elif [ $TRAVIS_BRANCH == 'master' ]
- then
- echo "Push to master, deploying to beta"
- EXPORT PLAY_TRACK='beta'
- "./gradlew publishApkRelease"
- elif [ $TRAVIS_BRANCH == 'develop' ]
- echo "Push to develop, deploying to alpha"
- then
- EXPORT PLAY_TRACK='alpha'
- "./gradlew publishApkRelease"
- else
- echo "Push to $TRAVIS_BRANCH, not deploying"
- "./gradlew assembleProduction"
- fi
notifications:
  email: false
  slack:
    secure: etZCydhfzyqvEzMxPW0NqpEXAONJXQk4lSxuwuOiDxRpYOSzZBNOibzIpHdn3GyTbf/DWoy67RG5hpCdJc/jG9xJBVKv/jCo8Adt/lJAblXPu7C9FBOriJXva0CgBS7HSiWxr5sjteGAz5/Qmohjdf0u/CNFoZMpBlpEk80doqbFj/HfEfbF0EGDZegpYeskIs6A82rAuWQoSAPq7JW3/D1ykFtAVIl8YOYBpmQshmzyQyBrEExIg+ZmVbHmYerbkWSXkRW2UwcglFURWFmbg6EGNb5WeewvY/tuLVNm2KdvvUjy+mjjXwk2f/hbrGbc/dTOZ63F7D9CdWb4/1Ombjrh7p9Jry1KZlIeQXhYbBBdEIMdHhR1aYBJB63v9v8lpy4nqzK5TUPb6stisA2p80UZxhNmreON+lcun65pl2disc+mc+If5HZXmoayltULelTiVNvVosKu7N0gE2aoPYCbscsZ7sPtvqB1OjgIHYegwnjAsGEyakOp8PXvpZbTbIebfRbSmT+gzGV9ROJihj+rQ7uVgT6edG+wodNWNvx2jcvLwQbx58SwP4b3v69+zdIw2uEofzxxccc7rBvguaIqg7DzcG5OKnWJDxgBeyTmBagZJXd3UqPhV0ziuCB7cdIyw4HIbWHOiMCLZJ1KhlpN0jAU4oc1SmDcnXzlm9g=
