language: android
jdk: oraclejdk8
#sudo: required

android:
  components:
    - tools
    - tools
    - platform-tools

# The BuildTools version used by your project
    - build-tools-25.0.2

# The SDK version used to compile your project
    - android-25

    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build